/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wulee;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Vu
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        hidePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        inBrowseBt = new javax.swing.JButton();
        inPathLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        outBrowseBt = new javax.swing.JButton();
        outPathLb = new javax.swing.JLabel();
        hideBt = new javax.swing.JButton();
        unhidePane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WuLee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nhập văn bản muốn giấu:");

        inputTextTA.setColumns(20);
        inputTextTA.setRows(5);
        jScrollPane1.setViewportView(inputTextTA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Chọn ảnh phủ: ");

        inBrowseBt.setText("Duyệt tập tin");
        inBrowseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBrowseBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Chọn nơi lưu trữ ảnh giấu tin");

        outBrowseBt.setText("Duyệt tập tin");
        outBrowseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outBrowseBtActionPerformed(evt);
            }
        });

        hideBt.setText("Giấu tin");
        hideBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hidePaneLayout = new javax.swing.GroupLayout(hidePane);
        hidePane.setLayout(hidePaneLayout);
        hidePaneLayout.setHorizontalGroup(
            hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(hidePaneLayout.createSequentialGroup()
                        .addGroup(hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(inBrowseBt)
                            .addComponent(inPathLb)
                            .addComponent(jLabel4)
                            .addComponent(outBrowseBt)
                            .addComponent(outPathLb))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hidePaneLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(hideBt)
                .addGap(151, 151, 151))
        );
        hidePaneLayout.setVerticalGroup(
            hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inBrowseBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inPathLb)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outBrowseBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outPathLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(hideBt)
                .addContainerGap())
        );

        tabPane.addTab("Giấu tin", hidePane);

        javax.swing.GroupLayout unhidePaneLayout = new javax.swing.GroupLayout(unhidePane);
        unhidePane.setLayout(unhidePaneLayout);
        unhidePaneLayout.setHorizontalGroup(
            unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        unhidePaneLayout.setVerticalGroup(
            unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        tabPane.addTab("Trích xuất tin", unhidePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inBrowseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBrowseBtActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
//        chooser.setFileFilter(new FileFilter() {
//
//            @Override
//            public boolean accept(File f) {
//                if (f.getName().endsWith(".jpg") || f.getName().endsWith(".png"))
//                    return true;
//                return false;
//            }
//
//            @Override
//            public String getDescription() {
//                return null;
//            }
//        });
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            input = chooser.getSelectedFile();
            inPathLb.setText(input.getAbsolutePath());
        }
    }//GEN-LAST:event_inBrowseBtActionPerformed

    private void outBrowseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outBrowseBtActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            output = chooser.getSelectedFile();
            outPathLb.setText(output.getAbsolutePath());
        }
    }//GEN-LAST:event_outBrowseBtActionPerformed

    private void hideBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBtActionPerformed
        // TODO add your handling code here:
        if ((input==null) || (output==null) || (inputTextTA.getText().length()==0)){
            JOptionPane.showMessageDialog(null, "Hãy nhập đủ thông tin đầu vào");
        }else{
            String s = inputTextTA.getText();
             Matrix key = new Matrix(new int[][]{
                 {1, 0, 0, 1},
                 {1, 1, 0, 1},
                 {0, 0, 0, 1},
                 {0, 0, 1, 1},
            });
            try {
                Utils.copyFile(input, output);
                WuLee.hideInformation(s, key, input);
            } catch (IOException ex) {
                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Giấu tin thành công");
        }
    }//GEN-LAST:event_hideBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MainGui().setVisible(true);
            }
        });
    }
    
    private File input;
    private File output;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hideBt;
    private javax.swing.JPanel hidePane;
    private javax.swing.JButton inBrowseBt;
    private javax.swing.JLabel inPathLb;
    private javax.swing.JTextArea inputTextTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton outBrowseBt;
    private javax.swing.JLabel outPathLb;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JPanel unhidePane;
    // End of variables declaration//GEN-END:variables
}
