/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wulee;

import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Vu
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        hidePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        inBrowseBt = new javax.swing.JButton();
        inPathLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        outBrowseBt = new javax.swing.JButton();
        outPathLb = new javax.swing.JLabel();
        hideBt = new javax.swing.JButton();
        unhidePane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inUnhideBrowserBt = new javax.swing.JButton();
        inUnhidePathLb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textLengtTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        unhideBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WuLee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nhập văn bản muốn giấu");

        inputTextTA.setColumns(20);
        inputTextTA.setRows(5);
        jScrollPane1.setViewportView(inputTextTA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Chọn ảnh phủ");

        inBrowseBt.setText("Duyệt tập tin");
        inBrowseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inBrowseBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Chọn nơi lưu trữ ảnh giấu tin");

        outBrowseBt.setText("Duyệt tập tin");
        outBrowseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outBrowseBtActionPerformed(evt);
            }
        });

        hideBt.setText("Giấu tin");
        hideBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hidePaneLayout = new javax.swing.GroupLayout(hidePane);
        hidePane.setLayout(hidePaneLayout);
        hidePaneLayout.setHorizontalGroup(
            hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(hidePaneLayout.createSequentialGroup()
                        .addGroup(hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(inBrowseBt)
                            .addComponent(inPathLb)
                            .addComponent(jLabel4)
                            .addComponent(outBrowseBt)
                            .addComponent(outPathLb))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hidePaneLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(hideBt)
                .addGap(151, 151, 151))
        );
        hidePaneLayout.setVerticalGroup(
            hidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inBrowseBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inPathLb)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outBrowseBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outPathLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(hideBt)
                .addContainerGap())
        );

        tabPane.addTab("Giấu tin", hidePane);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Chọn ảnh đã giấu tin");

        inUnhideBrowserBt.setText("Duyệt tập tin");
        inUnhideBrowserBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inUnhideBrowserBtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Độ dài UTF8 của mẩu tin:");

        textLengtTf.setColumns(5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Văn bản");

        outputTA.setEditable(false);
        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane2.setViewportView(outputTA);

        unhideBt.setText("Trích tin");
        unhideBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unhideBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unhidePaneLayout = new javax.swing.GroupLayout(unhidePane);
        unhidePane.setLayout(unhidePaneLayout);
        unhidePaneLayout.setHorizontalGroup(
            unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unhidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(unhidePaneLayout.createSequentialGroup()
                        .addGroup(unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(inUnhideBrowserBt)
                            .addComponent(inUnhidePathLb)
                            .addComponent(jLabel7)
                            .addGroup(unhidePaneLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textLengtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(unhidePaneLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(unhideBt)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        unhidePaneLayout.setVerticalGroup(
            unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unhidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inUnhideBrowserBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inUnhidePathLb)
                .addGap(29, 29, 29)
                .addGroup(unhidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textLengtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(unhideBt)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabPane.addTab("Trích xuất tin", unhidePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inBrowseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inBrowseBtActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Image", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            input = chooser.getSelectedFile();
            inPathLb.setText(input.getAbsolutePath());
        }
    }//GEN-LAST:event_inBrowseBtActionPerformed

    private void outBrowseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outBrowseBtActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Image", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            output = chooser.getSelectedFile();
            outPathLb.setText(output.getAbsolutePath());
        }
    }//GEN-LAST:event_outBrowseBtActionPerformed

    private void hideBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBtActionPerformed
        // TODO add your handling code here:
        String s;
        if ((input == null) || (output == null) || (inputTextTA.getText().trim().length() == 0)) {
            JOptionPane.showMessageDialog(null, "Hãy nhập đủ thông tin đầu vào");
        } else {
            s = inputTextTA.getText();
            Matrix key = new Matrix(new int[][]{
                {1, 0, 0, 1},
                {1, 1, 0, 1},
                {0, 0, 0, 1},
                {0, 0, 1, 1},});
            try {
                Utils.copyFile(input, output);
                WuLee.hideInformation(s, key, output);
            } catch (IOException ex) {
                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                JOptionPane.showMessageDialog(null, "Giấu tin thành công\nĐộ dài mẩu tin : "+Integer.toString(s.trim().getBytes("UTF-8").length));
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_hideBtActionPerformed

    private void inUnhideBrowserBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inUnhideBrowserBtActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Image", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            inputUnhide = chooser.getSelectedFile();
            inUnhidePathLb.setText(inputUnhide.getAbsolutePath());
        }

    }//GEN-LAST:event_inUnhideBrowserBtActionPerformed

    private void unhideBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unhideBtActionPerformed
        // TODO add your handling code here:
        String message;
        if (inputUnhide == null || textLengtTf.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Hãy nhập đủ tham số đầu vào");
        } else {
            try {
                int length = Integer.parseInt(textLengtTf.getText());
                String s = inputTextTA.getText();
                Matrix key = new Matrix(new int[][]{
                    {1, 0, 0, 1},
                    {1, 1, 0, 1},
                    {0, 0, 0, 1},
                    {0, 0, 1, 1},});
                message = WuLee.readInformation(key, inputUnhide, length);
                outputTA.setText(message);
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Độ dài mẩu tin phải là số nguyên");
            } catch (IOException ex) {
                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_unhideBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MainGui().setVisible(true);
            }
        });
    }
    private File input;
    private File output;
    private File inputUnhide;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hideBt;
    private javax.swing.JPanel hidePane;
    private javax.swing.JButton inBrowseBt;
    private javax.swing.JLabel inPathLb;
    private javax.swing.JButton inUnhideBrowserBt;
    private javax.swing.JLabel inUnhidePathLb;
    private javax.swing.JTextArea inputTextTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton outBrowseBt;
    private javax.swing.JLabel outPathLb;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTextField textLengtTf;
    private javax.swing.JButton unhideBt;
    private javax.swing.JPanel unhidePane;
    // End of variables declaration//GEN-END:variables
}
